firebase/firebase-admin-java

src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
src/main/java/com/google/firebase/database/tubesock/WebSocket.java
src/main/java/com/google/firebase/database/tubesock/WebSocketReceiver.java
src/main/java/com/google/firebase/database/tubesock/WebSocketWriter.java

Creating Websocket reader and writer threads lazily to avoid the thread leak described in #29; Handling thread interrupts from Websocket receiver thread (not comprehensive due to the blocking nature of IO calls; Reducing the default jitter factor to 25%

Fixing a Thread Leak in Database Client Code (Related to #29)

---

src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/ProviderUserInfo.java
src/main/java/com/google/firebase/auth/User.java
src/main/java/com/google/firebase/auth/UserInfo.java
src/main/java/com/google/firebase/auth/UserRecord.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

Following changes were suggested at the API review:
* Introduce `UserInfo` public interface type
* Rename `User` to `UserRecord`
* Rename `User.Builder` to `UserRecord.CreateRequest`
* Rename `User.Updater` to `UserRecord.UpdateRequest`
* Drop `ProviderUserInfo` from the public API
* Implement `UserInfo` at both `UserRecord` and `ProviderUserInfo`

Refactoring the User Management API

---

pom.xml

Fixing #40 
Our source distribution (firebase-admin-source.jar uploaded to Maven) does not actually contain any source files. This was the behavior we had configured in the pre-open source days. Now that we are open source, we should include source files in the distribution.

Updating the build configuration to include source files

---

pom.xml
src/test/java/com/google/firebase/auth/internal/FirebaseTokenVerifierTest.java
src/test/java/com/google/firebase/tasks/TaskImplTest.java
src/test/java/com/google/firebase/tasks/TasksTest.java

Dropped test dependency on Hamcrest library

---

src/main/java/com/google/firebase/FirebaseOptions.java
src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseCredentials.java
src/test/java/com/google/firebase/FirebaseOptionsTest.java

* Exposed protected factory methods in `FirebaseCredentials`, which accept `JsonFactory` and `HttpTransport` arguments.
* Added `setJsonFactory()` and `setHttpTransport()` methods to `FirebaseOptions`.
Related to #35

Making JsonFactory and HttpFactory Configurable

---

src/main/java/com/google/firebase/FirebaseApp.java
src/main/java/com/google/firebase/FirebaseOptions.java
src/test/java/com/google/firebase/FirebaseAppTest.java
src/test/java/com/google/firebase/FirebaseOptionsTest.java

* Removed `toString()`, `hashCode()` and `equals()` methods from `FirebaseOptions` class. These methods had been originally implemented to support some persistence requirements, which are no longer in use. We can consider adding these methods back if and when we decide to add persistence in the future.
* Removed the affected test cases.
* Changed `FirebaseApp.toString()` to no longer include options in the output.
See #38 for a related discussion

Removing toString, hashCode and equals methods from FirebaseOptions

---

src/test/java/com/google/firebase/auth/FirebaseAuthTest.java

`FirebaseAuthTest` has several test cases that we conditionally skip. This can be implemented cleanly using Junit 4's [Assume](https://github.com/junit-team/junit4/wiki/assumptions-with-assume) construct.

Using JUnit assumptions to skip tests instead of explicit returns

---

src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java

Generating a warning if the credential returns an invalid OAuth2 token to the database client code.
See b/35096493 for more context.

Improved Error Logging in Database

---

src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/ProviderUserInfo.java
src/main/java/com/google/firebase/auth/UserInfo.java
src/main/java/com/google/firebase/auth/UserRecord.java
src/main/java/com/google/firebase/auth/internal/GetAccountInfoResponse.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/resources/getUser.json

* Added `FirebaseAuth.getUserByPhoneNumber()` method.
* Added `setPhoneNumber()` method to `CreateRequest` and `UpdateRequest` types.
* Exposing phone number via `UserInfo` and `UserRecord` types.
go/firebase-java-phone-auth

Implementing Phone Auth Support

---

pom.xml

Adding `google-cloud-storage` to the project classpath has somehow broken our javadoc generation tools:
```
Constructing Javadoc information...
1 error
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.764 s
[INFO] Finished at: 2017-08-11T12:15:41-07:00
[INFO] Final Memory: 58M/1617M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:aggregate (default) on project firebase-admin: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - javadoc: error - In doclet class com.google.doclava.Doclava,  method start …
```

Adding an extra dependency to javadoc classpath

---

src/main/java/com/google/firebase/database/core/Repo.java

Currently these errors are simply swallowed and ignored. This PR handles them by logging the errors. Resolves #69.

Handling errors thrown by Transaction.Handler.onComplete()

---

pom.xml
src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/database/DatabaseReference.java
src/main/java/com/google/firebase/database/OnDisconnect.java
src/main/java/com/google/firebase/internal/TaskToApiFuture.java
src/main/java/com/google/firebase/tasks/Task.java
src/test/java/com/google/firebase/FirebaseAppTest.java
src/test/java/com/google/firebase/TestOnlyImplFirebaseTrampolines.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/database/integration/DataTestIT.java
src/test/java/com/google/firebase/database/integration/EventTestIT.java
src/test/java/com/google/firebase/database/integration/FirebaseDatabaseAuthTestIT.java
src/test/java/com/google/firebase/database/integration/InfoTestIT.java
src/test/java/com/google/firebase/database/integration/OrderTestIT.java
src/test/java/com/google/firebase/database/integration/QueryTestIT.java
src/test/java/com/google/firebase/database/integration/RulesTestIT.java
src/test/java/com/google/firebase/database/integration/TransactionTestIT.java
src/test/java/com/google/firebase/testing/IntegrationTestUtils.java

This is the first phase of migration to `ApiFutures` (go/firebase-admin-java-threads). This PR:
1. Deprecates the `Task` API.
2. Adds a set of new methods to `FirebaseAuth` that returns `ApiFutures`. 
3. Updates the test cases to use `ApiFutures` where appropriate.
I'm not touching the `FirebaseCredential` interface, since that is going to be deprecated separately.
`DatabaseReference` and `OnDisconnect` classes also have some methods that return `Tasks`. Any ideas on how to deal with them will be appreciated. We can introduce a set of new methods that return `ApiFutures` here as well.  But that results in the following migration path which is not ideal:
```
// Phase 1 (No breaking changes)
class DatabaseReference {
public Task<Void> setValue(Object value);
public ApiFuture<Void> …
```

Deprecated the Task API and introduced ApiFutures

---

.gitignore
CONTRIBUTING.md
src/test/java/com/google/firebase/testing/IntegrationTestUtils.java

Up until now we have required passing integration test credentials explicitly as system properties:
```
-Difrebase.it.certificate=path/to/key.json -Dfirebase.it.apikey=my_api_key
```
However, it is much easier if the test suite can simply load these parameters implicitly, from well-known files in the local file system. That way the development environment can be set up once with the required files, and the test suite can be invoked without additional parameters from there on.
This PR modifies the test suite to load the integration test credentials from `integration_cert.json` and `integration_apikey.txt` files. We've been following a similar convention in other admin SDKs, which has proven to be a lot easier to manage.

Load integration test credentials from well-known files

---

pom.xml

This also picks up the latest version of gax, so we no longer have to specify it explicitly.
Related to https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2496

Updating GCS dependency version

---

src/main/java/com/google/firebase/cloud/FirestoreClient.java
src/main/java/com/google/firebase/cloud/StorageClient.java

Updated API docs for Cloud clients.

Updated Firestore and GCS docs

---

pom.xml

Making yet another config change to get the Javadoc generation working (this is starting to become a problem). The `error_prone` library is now in our classpath (transitive dependency via gRPC). But now we need to add `j2objc-annotations` to get the javadoc plugin working.
I did some additional testing, and this seems to be a bug in `doclava`. The regular Maven javadoc plugin works fine without these additional configs. I've reached out to the doclava team to get some help.

Fixing a javadoc generator failure

---

pom.xml
src/test/java/com/google/firebase/CodeCoverageReporter.java

Adding a new Maven profile for generating code coverage reports. The profile can be activated by running:
```
mvn test -Djacoco
```
This produces a set of HTML and CSV reports in the `target/jacoco-ut` directory. The `CodeCoverageReporter` class then parses the CSV report, and prints a summary to the console:
```
-------------------------------------------------------------------------
Jacoco Coverage Report
-------------------------------------------------------------------------
com.google.firebase                                 1019/1271    80.17%
com.google.firebase.auth                            1231/1741    70.71%
com.google.firebase.auth.internal                     695/726    95.73%
com.google.firebase.cloud                               57/96    59.38% …
```

Code Coverage Integration

---

src/test/java/com/google/firebase/auth/FirebaseAuthIT.java

`getCustomClaims()` returns an empty map (not null) when there are no claims.

Fixed integration tests for auth

---

src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/internal/HttpErrorResponse.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

User management API currently returns a set of custom error codes specific to Java Admin SDK. This PR changes the implementation to:
* parse the error messages/codes sent by the ID toolkit backend service, and
* map errors to [well-defined](https://firebase.google.com/docs/auth/admin/errors) Admin SDK error codes.

Improved error handling for user management API

---

src/test/java/com/google/firebase/FirebaseAppTest.java
src/test/java/com/google/firebase/auth/FirebaseCredentialsTest.java
src/test/java/com/google/firebase/testing/TestUtils.java

ADC are essentially singletons. Therefore whatever the test case that initializes it first wins. Now that we have at least 2 separate test classes that use ADC, we need a way to ensure that they don't conflict. This fix takes care of that.

Fixing an issue with application default credentials during tests

---

src/main/java/com/google/firebase/FirebaseApp.java

We currently have the following state assertion in the `FirebaseApp` class:
```
checkState(!deleted.get(), "FirebaseApp '%s' was deleted", this);
```
With guava 20.0 (which is what we depend on), the above invocation gets bound to the following method signature at the compile time:
```
checkState(boolean, String, Object)
```
[API ref](https://google.github.io/guava/releases/20.0/api/docs/com/google/common/base/Preconditions.html#checkState-boolean-java.lang.String-java.lang.Object-)
This signature, it seems, is not present in some of the guava versions out there. It is notably absent in all guava distributions older than 20.0, and also from some of the other backports in circulation such as `guava-jdk5`. As a result, when there are conflicting guava binaries in an application classpath a …

Preventing possible runtime errors due to Guava version conflicts

---

README.md

The old badge (https://javadoc-emblem.rhcloud.com) is no longer available. Switching to a new one.

Fixing the Javadoc badge on README

---

CHANGELOG.md
src/main/java/com/google/firebase/FirebaseOptions.java
src/test/java/com/google/firebase/FirebaseOptionsTest.java

Also throwing an error if the bucket name contains `gs://` prefix

Updated documentation for StorageBucket option

---

CHANGELOG.md
src/main/java/com/google/firebase/database/core/ThreadPoolEventTarget.java
src/test/java/com/google/firebase/database/TestHelpers.java

Logging errors thrown by event handlers. Resolves #79. Without this errors thrown by event handlers are silently discarded.
```
ref.addListenerForSingleValueEvent(new ValueEventListener() {
@Override
public void onDataChange(DataSnapshot snapshot) {
throw new RuntimeException("test error");
}
@Override
public void onCancelled(DatabaseError error) {
}
});
```
```
[FirebaseDatabaseEventTarget] ERROR com.google.firebase.database.core.ThreadPoolEventTarget - Event handler threw an exception
java.lang.RuntimeException: test error
at com.google.firebase.database.integration.EventTestIT$17.onDataChange(EventTestIT.java:1160)
at com.google.firebase.database.Query$1.onDataChange(Query.java:182)
at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:77)
at …
```

Logging any errors encountered while executing a DB event handler

---

src/main/java/com/google/firebase/messaging/Message.java
src/test/java/com/google/firebase/messaging/MessageTest.java

The new FCM API does not accept topic names prefixed with `/topics/`. But we can easily check for this in the SDK and remove it. This results in a better and consistent dev experience since the other methods in this API accepts prefixed topic names.

Accept prefixed topic names

---

CHANGELOG.md
src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java

The error codes defined in https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode are embedded in the details section of the error response. The top-level error code (`status` field in the response) may take additional values such as `NOT_FOUND` and `UNAUTHENTICATED` (the so called canonical error codes):
```
{
"error":{
"code":404,
"message":"Requested entity was not found.",
"status":"NOT_FOUND",
"details: [
{
"@type":"type.googleapis.com/google.firebase.fcm.v1.FcmError",
"errorCode":"UNREGISTERED"
}
]
}
}
```
This PR updates the FCM implementation to handle these additional error codes and map them to correct client-side errors.

Handling FCM canonical error codes

---

src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/ListUsersPage.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/ListUsersPageTest.java
src/test/java/com/google/firebase/testing/MultiRequestMockHttpTransport.java
src/test/java/com/google/firebase/testing/TestResponseInterceptor.java

Unit tests currently test the `FirebaseUserManager` internal class, but does not test the public API surface in `FirebaseAuth`. As a result the `com.google.firebase.auth` package has a test coverage of only 69%. This PR modifies the tests so that we test the public API surface, bringing the package test coverage to 91%. 
The overall test coverage goes from 81% to 82%.

Improved Auth Unit Test Coverage

---

src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/internal/FirebaseTokenVerifier.java

Construct the default GooglePublicKeysManager with the custom
httpTransport. This avoid error due to proxy.
Fixes #150

Add given httpTransport in GooglePublicKeysManager

---

src/main/java/com/google/firebase/database/connection/NettyWebSocketClient.java
src/main/java/com/google/firebase/database/connection/WebsocketConnection.java

There's a small delay between `channelInactive()` low-level event, and us calling `channel.close()`. The former executes on a Netty worker thread, while the latter is on the runloop. An outgoing `send()` may sneak through this window to cause a hard assertion failure. 
The old tubesock implementation handled this type of race conditions more gracefully, by simply logging the error and closing the connection for good. This PR essentially implements the same semantics on top of Netty.
b/74831164

Handling some WebSocket connection errors gracefully

---

src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java

Porting error handling improvement from https://github.com/firebase/firebase-admin-node/pull/246
Reading error code from the `details` section of the HTTP response when available.

Reading FCM error code from the details section

---

src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java

If an error response comes back with no content, the json factory throws a
NullPointerException when it attempts to read the response, which hides the
response code from the client.
fixes #166

Add handling of null response content

---

src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java
src/test/java/com/google/firebase/snippets/FirebaseMessagingSnippets.java

Also discovered an oversight/inconsistency in the `FirebaseAuth` API where the blocking API is incorrectly named `setCustomClaims()`. I'm deprecating this method immediately, and introducing the correctly names `setCustomUserClaims()` method.

Updating snippets to use the blocking APIs

---

CHANGELOG.md
src/main/java/com/google/firebase/FirebaseApp.java
src/main/java/com/google/firebase/cloud/FirestoreClient.java
src/main/java/com/google/firebase/iid/FirebaseInstanceId.java
src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
src/test/java/com/google/firebase/FirebaseAppTest.java

`GCLOUD_PROJECT` is no longer supported in some managed Google runtimes. `GOOGLE_CLOUD_PROJECT` is the new recommended environment variable.

Reading project ID from GOOGLE_CLOUD_PROJECT

---

src/test/java/com/google/firebase/snippets/FirebaseDatabaseSnippets.java

Second argument to `setValueAsync()` is a priority (type `Object`). Therefore the current snippet compiles, but does not work as expected.

Fixing an incorrect RTDB snippet

---

pom.xml

Maven reporting plugin generates several extra reports when generating API docs, which are of no use to us at the moment. But these reports take a long time to get compiled, and also produce copious amounts of errors:
```
[INFO] Generating "Dependencies" report    --- maven-project-info-reports-plugin:2.9
[WARNING] Failure to transfer io.grpc:grpc-core/maven-metadata.xml from http://central was cached in the local repository, resolution will not be reattempted until the update interval of nexus-deps has elapsed or updates are forced. Original error: Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to nexus-deps (http://central): central: Name or service not known
[WARNING] Failure to transfer io.grpc:grpc-core/maven-metadata.xml from http://central was cached in the …
```

Disable generation of additional Maven reports

---

src/main/java/com/google/firebase/FirebaseOptions.java
src/test/java/com/google/firebase/snippets/FirebaseAppSnippets.java

`GoogleCredentials` are required when creating `FirebaseOptions`. This PR makes this requirement explicit in the documentation and samples.
Resolves #234

Updated documentation and sample snippet

---

CHANGELOG.md
pom.xml
src/main/java/com/google/firebase/database/util/JsonMapper.java
src/test/java/com/google/firebase/database/connection/WebsocketConnectionTest.java
src/test/java/com/google/firebase/database/core/JvmAuthTokenProviderTest.java
src/test/java/com/google/firebase/database/util/JsonMapperTest.java

Remove Dependency on org.json:json Artifact (#113), Java 11 build problems (#243)

---

CHANGELOG.md
src/main/java/com/google/firebase/auth/internal/UploadAccountResponse.java
src/test/resources/importUsersError.json

Fix in the UploadAccountResponse object for mapping the error message.

Fix for the uploadAccountResponse for correct error message/reason

---

src/main/java/com/google/firebase/messaging/FirebaseMessagingClient.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java

Sets the `X-Client-Version` header for FCM requests. When sending batch requests, each of the child messages will carry the header.

Setting the X-Client-Version header for FCM

---

src/main/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImpl.java
src/main/java/com/google/firebase/projectmanagement/Scheduler.java
src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImplTest.java

Project management unit tests take several seconds due to the delay operations:
```
Running com.google.firebase.projectmanagement.FirebaseProjectManagementServiceImplTest
Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.068 sec - in com.google.firebase.projectmanagement.FirebaseProjectManagementServiceImplTest
```
This PR makes it possible to inject a `MockSleeper` and a `MockScheduler` so the delays can be mocked during tests:
```
Running com.google.firebase.projectmanagement.FirebaseProjectManagementServiceImplTest
Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.041 sec - in com.google.firebase.projectmanagement.FirebaseProjectManagementServiceImplTest
```

Speeding up the Project Management Unit Tests

---

NOTICE.txt
src/main/java/com/google/firebase/internal/DateUtils.java
src/main/java/com/google/firebase/internal/RetryUnsuccessfulResponseHandler.java
src/test/java/com/google/firebase/internal/DateUtilsTest.java

In #255 we used an Apache HTTP client API (`DateUtils`) to parse HTTP date headers. We have this library in our classpath at the moment as a transitive dependency of Google API client. But the Google API client is undergoing a refactor, and this dependency will be removed in a future release. In preparation for this, I'm creating our own `DateUtils` class by copying the related bit of code from the Apache HTTP client.
The original implementation in Apache HTTP client uses thread locals to cache the `SimpleDateFormat` instances, and use them in a thread safe manner. I used explicit locking instead, in order to avoid potential memory leaks that may arise from unreleased thread locals (other suggestions welcome).

Removing the hard dependency on Apache HTTP Client

---

src/main/java/com/google/firebase/database/utilities/encoding/CustomClassMapper.java

This ports the changes from https://github.com/firebase/firebase-android-sdk/pull/272 and updates the error messages in the RTDB client when a user attempts to serialize Number types that we cannot serialize to JSON.
Addresses: https://github.com/firebase/firebase-admin-java/issues/75

Reject non-standard Number classes during POJO serialization (RTDB)

---

cloudbuild.yaml
src/test/java/com/google/firebase/auth/FirebaseCustomTokenTest.java

We are experimenting with Cloud Build as a potential CI solution. This PR enables it for this repo.
The code change was needed to mock out an API call made to the Google metadata service. In Travis this API call fails, but in Cloud Build it actually makes a successful connection, unless we mock it out.

GCB Integration (Experimental)

---

src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

`FirebaseUserManager` requires a project ID. Currently we init the user manager when creating `FirebaseAuth`, which fails if a project ID is not specified. To be consistent with how other child-components are initialized in `FirebaseAuth`, I'm using the `Supplier` interface to defer the initialization of `FirebaseUserManager`.

Deferring the initialization of FirebaseUserManager

---

CHANGELOG.md
src/main/java/com/google/firebase/messaging/WebpushConfig.java
src/main/java/com/google/firebase/messaging/WebpushFcmOptions.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingClientImplTest.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingIT.java
src/test/java/com/google/firebase/messaging/MessageTest.java
src/test/java/com/google/firebase/snippets/FirebaseMessagingSnippets.java

WebpushFcmOptions is described in [documentation](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#webpushfcmoptions) but is not included in Java client.
Corresponding issue - #294

Add missing WebpushFcmOptions entity (as per documentation)

---

src/main/java/com/google/firebase/FirebaseApp.java
src/main/java/com/google/firebase/FirebaseOptions.java
src/main/java/com/google/firebase/database/FirebaseDatabase.java
src/main/java/com/google/firebase/database/connection/NettyWebSocketClient.java
src/main/java/com/google/firebase/database/connection/WebsocketConnection.java
src/main/java/com/google/firebase/database/core/Context.java
src/main/java/com/google/firebase/database/core/DatabaseConfig.java
src/main/java/com/google/firebase/database/core/JvmAuthTokenProvider.java
src/main/java/com/google/firebase/database/util/EmulatorHelper.java
src/main/java/com/google/firebase/database/utilities/Utilities.java
src/test/java/com/google/firebase/FirebaseAppTest.java
src/test/java/com/google/firebase/FirebaseOptionsTest.java
src/test/java/com/google/firebase/database/FirebaseDatabaseTest.java
src/test/java/com/google/firebase/database/util/EmulatorHelperTest.java
src/test/java/com/google/firebase/database/utilities/UtilitiesTest.java
src/test/java/com/google/firebase/testing/TestUtils.java

This PR makes it possible for the Java admin SDK to talk to the RTDB emulator instead of the actual database instance.
This can happen in the following fashion:-
1. If the user passes in a valid emulator URL (http scheme only, host can't contain `firebaseio.com`, has the `ns` query parameter)
2. Else, if the environment variable `FIREBASE_RTDB_EMULATOR_HOST` is set to a value of the form `host:port`.
If either 1. or 2. is true, we decide to talk to the RTDB emulator. In such cases, we 
- provide a valid emulator URL (either by replacing the supplied URL or making a new one)
- replace existing credentials with `EmulatorCredentials`, which use `owner` as the access token.
URL replacement happens in three places:- 
1. while constructing `FirebaseOptions` instances in `FirebaseApp`
2. when a …

feat(rtdb): Connect to RTDB emulator when valid emulator URL is passed OR env vars are set correctly

---

src/test/java/com/google/firebase/FirebaseAppTest.java

Not sure how, but the recent changes to database tests is causing a test failure in some environments:
```
Running com.google.firebase.database.FirebaseDatabaseTest
Tests run: 10, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.052 sec <<< FAILURE! - in com.google.firebase.database.FirebaseDatabaseTest
testDbUrlIsEmulatorUrlForDbRefWithPath(com.google.firebase.database.FirebaseDatabaseTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.IllegalArgumentException: Failed to load settings from the system's environment variables
at com.google.firebase.database.FirebaseDatabaseTest.testDbUrlIsEmulatorUrlForDbRefWithPath(FirebaseDatabaseTest.java:252)
Caused by: com.fasterxml.jackson.core.JsonParseException: 
Unexpected character (',' (code 44)): was expecting double-quote to start field …
```

Fixing an intermittent test failure

---

src/main/java/com/google/firebase/messaging/Notification.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingIT.java
src/test/java/com/google/firebase/messaging/MessageTest.java

Add a builder for Notification class.
Mark the existing two constructors for the Notification class as deprecated. 
Adjust the tests.

feat(fcm): Added a `Builder` for constructing `Notification` objects

---

pom.xml

RELEASE NOTE: Upgraded Cloud Firestore dependency version to 1.21.0.
RELEASE NOTE: Upgraded Cloud Storage dependency version to 1.91.0.
Resolves #310

fix: Upgraded Firestore and GCS

---

CONTRIBUTING.md
src/main/java/com/google/firebase/auth/ExportedUserRecord.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/ListUsersPageTest.java

Base64 'REDACTED' passwords look like passwords hashes, but aren't, leading to
potential confusion.
Additionally, added docs to CONTRIBUTING.md detailing how to add the
permission that causes password hashes to be properly returned as well
as adjusting the test failure message should the developer not add that
permission.
b/141189502

Remove (base64) 'REDACTED' passwords from user records.

---

src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
src/main/java/com/google/firebase/messaging/MulticastMessage.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingIT.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java
src/test/java/com/google/firebase/messaging/MulticastMessageTest.java
src/test/java/com/google/firebase/snippets/FirebaseMessagingSnippets.java

Increase the multicast request count limit to 500.
* Updated the related tests.
RELEASE NOTE: Number of messages per batch increased to 500.

fix(fcm): Increase the multicast request count limit to 500.

---

src/main/java/com/google/firebase/messaging/AndroidNotification.java

- Fix a typo in `AndroidNotification`

Fix a typo in AndroidNotification

---

src/main/java/com/google/firebase/auth/hash/Md5.java
src/main/java/com/google/firebase/auth/hash/Sha1.java
src/main/java/com/google/firebase/auth/hash/Sha256.java
src/main/java/com/google/firebase/auth/hash/Sha512.java
src/test/java/com/google/firebase/auth/UserImportHashTest.java
src/test/java/com/google/firebase/auth/hash/InvalidHashTest.java

Port of https://github.com/firebase/firebase-admin-node/pull/677

Reject rounds=0 for SHA1 hashes

---

src/main/java/com/google/firebase/internal/DateUtils.java
src/test/java/com/google/firebase/internal/RetryUnsuccessfulResponseHandlerTest.java
src/test/java/com/google/firebase/messaging/MessageTest.java

No issue.
Current Date test is depend on Locale(GMT).
I ran the test on my local machine and it was not successful.
This is because the Japanese locale (JMT) is used.
I defined use Locale.US.
Fixed test
None

Fix Date test in another Locale

---

pom.xml

Will provide IN query features
RELEASE NOTE: fix(Cloud Firestore): Upgraded `google-cloud-firestore` dependency version to 1.31.0 which provides support for `IN` queries.

Upgrade Cloud Firestore dependency

---

src/main/java/com/google/firebase/messaging/FirebaseMessagingClientImpl.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingClientImplTest.java

RELEASE NOTE: SDK now correctly handles the `THIRD_PARTY_AUTH_ERROR` error code returned by the backend service when sending notifications to iOS and web targets.

fix(fcm): Correctly handling FCM THIRD_PARTY_AUTH_ERROR error code

---

src/test/java/com/google/firebase/database/FirebaseDatabaseTest.java

Following test failures are observed when running on environments not set up for ADC:
```
testDbUrlIsEmulatorUrlForDbRefWithPath(com.google.firebase.database.FirebaseDatabaseTest)  Time elapsed: 0.13 sec  <<< ERROR!
java.lang.IllegalStateException: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
at com.google.firebase.database.FirebaseDatabaseTest.testDbUrlIsEmulatorUrlForDbRefWithPath(FirebaseDatabaseTest.java:252)
Caused by: java.io.IOException: The Application Default …
```

Fixing some failing RTDB tests

---

src/main/java/com/google/firebase/messaging/AndroidNotification.java
src/test/java/com/google/firebase/messaging/MessageTest.java

- Set the timezone to always be UTC.
- Pending zeros after the millisecond digits to the right instead of left.
RELEASE NOTE: `AndroidNotification` class now correctly formats the `event_time` field sent to the Cloud Messaging service.
Resolves #337

fix(fcm): Fix issues in event_time timestamp parsing

---

.opensource/project.json

The .NET SDK was missing from project.json, so this change simply adds it.

 Update project.json to include the .NET SDK.

---

src/main/java/com/google/firebase/ErrorCode.java
src/main/java/com/google/firebase/FirebaseException.java
src/main/java/com/google/firebase/IncomingHttpResponse.java
src/main/java/com/google/firebase/OutgoingHttpRequest.java
src/test/java/com/google/firebase/FirebaseAppTest.java
src/test/java/com/google/firebase/FirebaseExceptionTest.java
src/test/java/com/google/firebase/IncomingHttpResponseTest.java
src/test/java/com/google/firebase/OutgoingHttpRequestTest.java
src/test/java/com/google/firebase/testing/TestUtils.java

Starting to implement the error handling revamp. Since this contains sweeping breaking changes, I'm moving the implementation to a separate v7 branch.
* Added `ErrorCode`, `IncomingHttpResponse` and `OutgoingHttpRequest` types.
* Exposed error code and http response from the `FirebaseException` base class.
* Deprecated the old constructors in `FirebaseException`. These will be removed once the error handling revamp is fully implemented.
go/firebase-error-handling-java

Added core types for the error handling revamp

---

src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

Enabled automatic retries for failing HTTP calls in `FirebaseUserManager`. 
RELEASE NOTE: User management APIs in the `FirebaseAuth` class now automatically retries operations that fail due to retry-eligible HTTP errors.

fix(auth): Enabled automatic retries for FirebaseUserManager

---

src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/ListTenantsPage.java
src/main/java/com/google/firebase/auth/Tenant.java
src/main/java/com/google/firebase/auth/internal/ListTenantsResponse.java
src/test/java/com/google/firebase/auth/ListTenantsPageTest.java

This pull request adds ListTenantsPage (and some supporting code) as part of adding multi-tenancy support (see issue #332).
This code was very largely based off of ListUsersPage and ListUsersPageTest.

Add ListTenantsPage class.

---

src/main/java/com/google/firebase/iid/FirebaseInstanceId.java
src/main/java/com/google/firebase/iid/FirebaseInstanceIdException.java
src/main/java/com/google/firebase/internal/HttpRequestInfo.java
src/test/java/com/google/firebase/iid/FirebaseInstanceIdTest.java

This is not a OnePlatform API, so we extend the error handler directly from `AbstractHttpErrorHandler` class.

Error handling revamp for FirebaseInstanceId API

---

src/main/java/com/google/firebase/internal/ApiClientUtils.java
src/main/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImpl.java
src/test/java/com/google/firebase/internal/ApiClientUtilsTest.java
src/test/java/com/google/firebase/internal/TestApiClientUtils.java
src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImplTest.java

Enables automatic HTTP retries for the `FirebaseProjectManagement` API. We disable retries for unit tests for faster execution of tests.
RELEASE NOTE: Project management APIs in the `FirebaseProjectManagement` class now automatically retries operations that fail due to retry-eligible HTTP errors.

fix: Enabled automatic HTTP retries for FirebaseProjectManagement

---

src/main/java/com/google/firebase/auth/AuthErrorCode.java
src/main/java/com/google/firebase/auth/FirebaseAuthException.java
src/main/java/com/google/firebase/auth/FirebaseTokenUtils.java
src/main/java/com/google/firebase/auth/FirebaseTokenVerifierImpl.java
src/main/java/com/google/firebase/auth/RevocationCheckDecorator.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/auth/FirebaseTokenVerifierImplTest.java
src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java

Implementing the error handling revamp of the token verification APIs (`verifyIdToken()` and `verifySessionCookie()`)
1. Introduced several new Auth error codes to cover the new use cases.
2. Removed the old string error code from `FirebaseAuthException`. That's no longer used anywhere.
3. Added unit tests for token revocation checks, which we were missing until now.

Error handling revamp for token verification APIs

---

src/main/java/com/google/firebase/auth/AuthErrorHandler.java
src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseAuthException.java
src/main/java/com/google/firebase/auth/internal/CryptoSigner.java
src/main/java/com/google/firebase/auth/internal/CryptoSigners.java
src/main/java/com/google/firebase/auth/internal/FirebaseTokenFactory.java
src/test/java/com/google/firebase/auth/internal/CryptoSignersTest.java
src/test/java/com/google/firebase/auth/internal/FirebaseTokenFactoryTest.java

This finalizes the error handling revamp for the `FirebaseAuth` API.

Error handling revamp for the custom token creation API

---

src/main/java/com/google/firebase/auth/Tenant.java
src/main/java/com/google/firebase/auth/UserRecord.java
src/test/java/com/google/firebase/auth/ListTenantsPageTest.java
src/test/java/com/google/firebase/auth/TenantTest.java

This pull request adds some things to the Tenant class and adds a few unit tests. This is part of the initiative to adding multi-tenancy support (see issue #332).
It's worth noting that these changes deviate from the API design doc. I realized that the updateTenant method in my design doc doesn’t match the design of the existing updateUser method. To fix this, I'm adding the tenantId to Tenant.UpdateRequest.
This PR also removes the usage of AutoValue since using it was going to deviate too much from the design of the request classes in UserRecord. This change will also make it easier to do JSON serialization when we sending the requests.

Add updateRequest method to Tenant class and add unit tests.

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/ListTenantsPage.java
src/main/java/com/google/firebase/auth/TenantManager.java
src/main/java/com/google/firebase/auth/internal/ListTenantsResponse.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/resources/listTenants.json

This pull request adds the TenantManager class. The listTenants operation has been added and is wired through. I've added the relevant unit tests to FirebaseUserManagerTest (based off of the listUsers unit tests). This is part of the initiative to adding multi-tenancy support (see issue #332).

Create TenantManager class and wire through listTenants operation.

---

src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/TenantManager.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

This pull request add deleteTenant to the TenantManager class. I've added the relevant unit tests to FirebaseUserManagerTest (based off of the getTenant unit test). This is part of the initiative to adding multi-tenancy support (see issue #332).
REST API: https://identitytoolkit.googleapis.com/$discovery/rest?version=v2

Add deleteTenant operation to TenantManager.

---

src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/TenantManager.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/resources/getTenant.json

This pull request add getTenant to the TenantManager class. I've added the relevant unit tests to FirebaseUserManagerTest (based off of the getUser unit tests). This is part of the initiative to adding multi-tenancy support (see issue #332).
REST API: https://identitytoolkit.googleapis.com/$discovery/rest?version=v2

Add getTenant operation to TenantManager.

---

src/main/java/com/google/firebase/internal/ErrorHandlingHttpClient.java
src/main/java/com/google/firebase/projectmanagement/FirebaseProjectManagementException.java
src/main/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImpl.java
src/main/java/com/google/firebase/projectmanagement/HttpHelper.java
src/test/java/com/google/firebase/internal/TestApiClientUtils.java
src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImplTest.java
src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementTest.java
src/test/java/com/google/firebase/projectmanagement/IosAppTest.java

Implemented the new error handling scheme for the project management API (go/firebase-error-handling-java).
I've managed to retain the existing context-aware error message format used in this API (i.e. error messages include app/project ID strings), while injecting the platform error code into them.
go/firebase-error-handling-java

Error handling revamp for the project management API

---

src/main/java/com/google/firebase/FirebaseException.java
src/main/java/com/google/firebase/auth/FirebaseAuthException.java
src/main/java/com/google/firebase/iid/FirebaseInstanceIdException.java
src/main/java/com/google/firebase/internal/AbstractPlatformErrorHandler.java
src/main/java/com/google/firebase/messaging/FirebaseMessagingException.java
src/main/java/com/google/firebase/projectmanagement/FirebaseProjectManagementException.java
src/test/java/com/google/firebase/FirebaseExceptionTest.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/auth/FirebaseTokenVerifierImplTest.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/internal/CryptoSignersTest.java
src/test/java/com/google/firebase/iid/FirebaseInstanceIdTest.java
src/test/java/com/google/firebase/internal/AbstractPlatformErrorHandlerTest.java
src/test/java/com/google/firebase/internal/ErrorHandlingHttpClientTest.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingClientImplTest.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingIT.java
src/test/java/com/google/firebase/messaging/InstanceIdClientImplTest.java
src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImplTest.java

Renaming the method and removing the deprecated constructors on `FirebaseException` class.

Renamed getErrorCodeNew() to getErrorCode()

---

src/main/java/com/google/firebase/messaging/InstanceIdClientImpl.java
src/test/java/com/google/firebase/messaging/InstanceIdClientImplTest.java

IID error responses do not contain a message, only an error code.

Handling IID error codes correctly

---

src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/Tenant.java
src/main/java/com/google/firebase/auth/TenantManager.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/TenantTest.java

This pull request adds some integration testing for all of the tenant operations in TenantManager. Several bugs were uncovered after running the tests, so these have been fixed. This is part of the initiative to adding multi-tenancy support (see issue #332).

Add integration tests for TenantManager operations.

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/TenantManager.java

This is part of the initiative to adding multi-tenancy support (see issue #332).

Add firebase auth destroy check before tenant operations.

---

src/main/java/com/google/firebase/messaging/BatchResponseImpl.java
src/main/java/com/google/firebase/messaging/FirebaseMessagingClientImpl.java
src/test/java/com/google/firebase/messaging/BatchResponseTest.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java

Resolves #388 
- Converts batch response to an interface
- Moves batch response implementation to BatchResponseImpl
- Update FirebaseMessagingClientImpl to use BatchResponseImpl

Testable BatchResponse

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseToken.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/TenantAwareFirebaseAuth.java
src/main/java/com/google/firebase/auth/TenantManager.java
src/main/java/com/google/firebase/auth/UserRecord.java
src/main/java/com/google/firebase/auth/internal/GetAccountInfoResponse.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/resources/getUser.json
src/test/resources/listUsers.json

This pull request make user operations tenant-aware. I've added some integration tests to ensure that this is correct correctly. This is part of the initiative to adding multi-tenancy support (see issue #332).

Make user operations tenant-aware.

---

CONTRIBUTING.md

This documentation was sourced from what I saw in https://github.com/firebase/firebase-admin-node/blob/master/CONTRIBUTING.md.

Mention set up required for the multitenancy integration tests.

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseToken.java
src/main/java/com/google/firebase/auth/FirebaseTokenUtils.java
src/main/java/com/google/firebase/auth/FirebaseTokenVerifierImpl.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/TenantAwareFirebaseAuth.java
src/main/java/com/google/firebase/auth/internal/FirebaseCustomAuthToken.java
src/main/java/com/google/firebase/auth/internal/FirebaseTokenFactory.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseTokenVerifierImplTest.java
src/test/java/com/google/firebase/auth/internal/FirebaseTokenFactoryTest.java

This pull request incorporates the tenant ID into the token generation and validation when using a tenant-aware client. This is part of the initiative to adding multi-tenancy support (see issue #332).

Add tenant-aware token generation and verification.

---

src/main/java/com/google/firebase/auth/AuthProviderConfig.java
src/main/java/com/google/firebase/auth/OidcProviderConfig.java
src/test/java/com/google/firebase/auth/OidcProviderConfigTest.java

This provider class only includes a `CreateRequest` inner class for the time being. An `UpdateRequest` inner class will be added in the future.
In addition to `OidcProviderConfig`, this pull request also includes a base class, which will be shared by a future `SamlProviderConfig` class.
This is part of adding multi-tenancy support (see issue #332).

Add OIDC Auth provider config class

---

src/main/java/com/google/firebase/auth/AuthProviderConfig.java
src/main/java/com/google/firebase/auth/OidcProviderConfig.java
src/main/java/com/google/firebase/auth/ProviderConfig.java
src/main/java/com/google/firebase/auth/Tenant.java
src/test/java/com/google/firebase/auth/OidcProviderConfigTest.java

This makes the base CreateRequest setters return the proper instance type, so that methods can be chained. This also makes it so that the provider ID can be parsed from the resource name.
A package private getProviderId() method was also added, which will be needed by the FirebaseUserManager class when the provider config operations are added there.
This work is part of adding multi-tenancy support (see issue #332).

Fix CreateRequest chaining and provider ID extraction.

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

This adds an operation to get OIDC provider configs (can be done using either the tenant-aware or standard Firebase client).
This work is part of adding multi-tenancy support (see issue #332).

Add operation to get OIDC provider configs.

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/OidcProviderConfig.java
src/main/java/com/google/firebase/auth/ProviderConfig.java
src/main/java/com/google/firebase/auth/Tenant.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/OidcProviderConfigTest.java

This adds an operation to update OIDC provider configs (can be done using either the tenant-aware or standard Firebase client).
This work is part of adding multi-tenancy support (see issue #332).

Add operation to update OIDC provider configs.

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/ListProviderConfigsPage.java
src/main/java/com/google/firebase/auth/ListTenantsPage.java
src/main/java/com/google/firebase/auth/ListUsersPage.java
src/main/java/com/google/firebase/auth/internal/ListOidcProviderConfigsResponse.java
src/main/java/com/google/firebase/auth/internal/ListProviderConfigsResponse.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/ListUsersPageTest.java
src/test/resources/listOidc.json

This adds an operation to list OIDC provider configs (can be done using either the tenant-aware or standard Firebase client). This is the last OIDC provider config operation that needs to be implemented.
This work is part of adding multi-tenancy support (see issue #332).
Please take note of the generics I have chosen to use in ListProviderConfigsPage. This should help reduce a lot of code duplication when it comes time to add support for SAML provider configs.

Add operation to list OIDC provider configs.

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java

Each asynchronous method is supposed to have a synchronous counterpart. This was supposed to be included in #404, when I added the operation to list OIDC provider configs.

Add missing listOidcProviderConfigs method.

---

src/main/java/com/google/firebase/auth/OidcProviderConfig.java
src/main/java/com/google/firebase/auth/ProviderConfig.java
src/test/java/com/google/firebase/auth/OidcProviderConfigTest.java

The OIDC Auth provider config ID must begin with "oidc.". This validation is being done in other APIs (e.g. Go), so we should do it here as well.
I've moved assertValidUrl to the base class so that it can be reused for `SamlProviderConfig`, once that class is added.

Add validation to provider config ID.

---

src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/TenantAwareFirebaseAuthIT.java
src/test/java/com/google/firebase/auth/TenantManagerIT.java

Using a JUnit `@Rule` to ensure that temporary user accounts are cleaned up in integration tests. This helps us avoid large try-finally blocks in tests.
I also moved couple of new tenant management tests to a new `TenantManagerIT` class.

fix(auth): Ensuring test user account cleanup with a Rule

---

pom.xml

Doclava doesn't seem to work well with the latest versions (v3) of the Maven Javadoc plugin. Generated output hierarchy is different from what we are used to. Until we figure out a proper solution, I'm defaulting to the v2 of the plugin.

chore: Setting the version of the Maven Javadoc plugin

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/ProviderConfigTestUtils.java
src/test/java/com/google/firebase/auth/TenantAwareFirebaseAuthIT.java

I've renamed the delete operation since we need separate methods for deleting OIDC and SAML provider configs.
I've also created a ProviderConfigTestUtils class to house shared logic between `TenantAwareFirebaseAuthIT` and `FirebaseAuthIT`, and I've added a `TemporaryProviderConfig` class to make it easier for provider configs to be cleaned up automatically. I've structured this class in such a way that we can easily tack on logic to cleanup SAML provider configs as well.
I've also decided to remove `testGetUserWithMultipleTenantIds`. I initially wrote this test to understand how tenant-aware auths and tenant-agnostic auths interacted with one another. In its existing state, it appears to be leaking created users, and in order to resolve this with `TemporaryUser`, we would need to declare …

Rename OIDC delete operation and refactor integration tests.

---

src/main/java/com/google/firebase/auth/OidcProviderConfig.java
src/main/java/com/google/firebase/auth/ProviderConfig.java
src/test/java/com/google/firebase/auth/OidcProviderConfigTest.java

This makes the formatting of the Javadoc comments more consistent, and it's now more clear when/why `IllegalArgumentException`s get thrown. This also adds validation to the provider ID in the `CreateRequest` to ensure that it has the correct prefix.'
Improvements were also made to the tests. The JSON string is now more readable, the parameters are now in the correct order for `assertEquals` calls, and the `IllegalArgumentException` tests have been properly fleshed out.

Make Javadoc comments consistent and validate provider ID in CreateRequest.

---

src/test/java/com/google/firebase/database/integration/OrderByTestIT.java

Updating the integration test to not reset the RTDB rules to public after each invocation.

chore: Updated integration tests to use non-public rules

---

checkstyle.xml
src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/ListProviderConfigsPage.java
src/main/java/com/google/firebase/auth/OidcProviderConfig.java
src/main/java/com/google/firebase/auth/internal/ListOidcProviderConfigsResponse.java
src/main/java/com/google/firebase/auth/internal/ListSamlProviderConfigsResponse.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/TenantAwareFirebaseAuthIT.java
src/test/resources/listSaml.json

Adds a list operation for SAML provider configs. I've included both unit tests and integration tests.

Add operation to list SAML provider configs.

---

src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/TenantManager.java

Moves the check in FirebaseUserManager.updateTenant outside CallableOperation in TenantManager.updateTenantOp, addressing an existing TODO.

Move check outside CallableOperation.

---

src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/TenantAwareFirebaseAuthIT.java
src/test/java/com/google/firebase/auth/UserTestUtils.java

I've refactored the test utilities we use for users in order to reduce code duplication, and I've also made `TenantAwareFirebaseAuthIT` use `TemporaryUser`.

Refactor user test utilities and use TemporaryUser in tenant-aware integration tests.

---

src/main/java/com/google/firebase/messaging/MulticastMessage.java
src/test/java/com/google/firebase/messaging/MulticastMessageTest.java

`MulticastMessage` does not seem to support `FcmOptions`. This PR introduces `FcmOptions` in `MulticastMessage`s. 
The implementation follows the same approach with the NodeJS SDK. 
https://github.com/firebase/firebase-admin-node/blob/master/src/messaging/messaging.ts#L361
Resolves #440

feat(fcm): Add FcmOptions on MulticastMessage

---

pom.xml
src/main/java/com/google/firebase/messaging/LightSettings.java
src/main/java/com/google/firebase/messaging/Notification.java
src/test/java/com/google/firebase/database/TestHelpers.java
src/test/java/com/google/firebase/database/ValueExpectationHelper.java
src/test/java/com/google/firebase/database/collection/RBTreeSortedMapTest.java
src/test/java/com/google/firebase/database/core/JvmAuthTokenProviderTest.java
src/test/java/com/google/firebase/database/integration/DataTestIT.java
src/test/java/com/google/firebase/testing/IntegrationTestUtils.java

Removed old test dependency and cleaned up some compiler warnings.

chore: Removing redundant test dependency

---

src/main/java/com/google/firebase/auth/hash/Bcrypt.java
src/main/java/com/google/firebase/auth/hash/HmacMd5.java
src/main/java/com/google/firebase/auth/hash/HmacSha1.java
src/main/java/com/google/firebase/auth/hash/HmacSha256.java
src/main/java/com/google/firebase/auth/hash/HmacSha512.java
src/main/java/com/google/firebase/auth/hash/Md5.java
src/main/java/com/google/firebase/auth/hash/Pbkdf2Sha256.java
src/main/java/com/google/firebase/auth/hash/PbkdfSha1.java
src/main/java/com/google/firebase/auth/hash/Sha1.java
src/main/java/com/google/firebase/auth/hash/Sha256.java
src/main/java/com/google/firebase/auth/hash/Sha512.java
src/main/java/com/google/firebase/auth/hash/StandardScrypt.java

While working on the .NET port of user imports I brought up the fact that these classes weren't final in the Java version; this PR revisits that idea.
API CHANGE: All public implementations of `UserImportHash` class are now marked `final`.

fix(auth): Make user import hashing classes final

---

pom.xml

* Importing guava, google-cloud-* and google-http-client via `libraries-bom`.
* Import google-api-client via `google-api-client-bom`
Resolves #450 
RELEASE NOTE: Admin SDK now imports all Google Cloud Platform dependencies via `com.google.cloud:libraries-bom`.

fix: Importing GCP dependencies via official BOMs

---

src/main/java/com/google/firebase/auth/internal/AuthHttpClient.java
src/main/java/com/google/firebase/internal/HttpRequestInfo.java
src/main/java/com/google/firebase/projectmanagement/HttpHelper.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/multitenancy/FirebaseTenantClientTest.java
src/test/java/com/google/firebase/internal/ErrorHandlingHttpClientTest.java
src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImplTest.java

Some HTTP methods (e.g. PATCH) requires some special handling due to the limitations in transport implementations like `NetHttpTransport`. This code is currently duplicated in several places. I'm moving this to `ErrorHandlingHttpClient` and `HttpRequestInfo` where it can be handled in a centralized manner.

fix: Handling http method override in ErrorHandlingHttpClient

---

src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java

Snippets for:
* https://cloud.google.com/identity-platform/docs/managing-providers-programmatically
* https://cloud.google.com/identity-platform/docs/multi-tenancy-managing-tenants

chore(auth): Added snippets for multitenancy and IdP management

---

pom.xml
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/internal/AuthHttpClient.java
src/main/java/com/google/firebase/auth/internal/CryptoSigners.java
src/main/java/com/google/firebase/iid/FirebaseInstanceId.java
src/main/java/com/google/firebase/internal/ErrorHandlingHttpClient.java
src/main/java/com/google/firebase/internal/HttpRequestInfo.java
src/main/java/com/google/firebase/messaging/FirebaseMessagingClientImpl.java
src/main/java/com/google/firebase/messaging/InstanceIdClientImpl.java
src/main/java/com/google/firebase/projectmanagement/HttpHelper.java
src/test/java/com/google/firebase/internal/ErrorHandlingHttpClientTest.java
src/test/java/com/google/firebase/messaging/InstanceIdClientImplTest.java

* Exposing `setInterceptor()` method on `ErrorHandlingHttpClient`. By handling it here, individual services no longer have to have a reference for `HttpResponseInterceptor`.
* Added support for serializing JSON request payloads at the `HttpRequestInfo`. This means individual services no longer have to handle this or even have a reference to a `JsonFactory`.
* Removing some leftover http method override code in `AuthHttpClient` (this became redundant as of #459)
* Upgraded Surefire and Jacoco test coverage dependencies.

fix: Handling JSON serialization/response interception at ErrorHandlingHttpClient

---

src/main/java/com/google/firebase/auth/AuthErrorCode.java
src/main/java/com/google/firebase/auth/internal/AuthErrorHandler.java
src/main/java/com/google/firebase/auth/internal/AuthHttpClient.java
src/main/java/com/google/firebase/auth/multitenancy/FirebaseTenantClient.java
src/main/java/com/google/firebase/auth/multitenancy/TenantManager.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/ProviderConfigTestUtils.java
src/test/java/com/google/firebase/auth/multitenancy/FirebaseTenantClientTest.java
src/test/java/com/google/firebase/auth/multitenancy/TenantManagerIT.java

* Added `CONFIGURATION_NOT_FOUND` error code. Also note that `TENANT_NOT_FOUND` error code was added while updating the v7 branch in #456.
* Made it possible to test `TenantManager` and `FirebaseTenantClient` with better mock responses.
* Updated error handling test cases to check for new error codes. I also updated some of the existing error handling tests to mock with more realistic errors (e.g. create operations do not usually fail with a NOT_FOUND error).

feat: Added new error codes for IdP management and multitenancy

---

src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

The constructor of FirebaseOptions.Builder` is deprecated in the v7 branch. This PR removes some of the lingering invocations of the old constructor.

fix: Removing some calls to deprecated APIs

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/internal/AuthHttpClient.java
src/main/java/com/google/firebase/auth/multitenancy/FirebaseTenantClient.java
src/main/java/com/google/firebase/internal/ErrorHandlingHttpClient.java
src/main/java/com/google/firebase/internal/HttpRequestInfo.java
src/main/java/com/google/firebase/projectmanagement/HttpHelper.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

A collection of somewhat related cleanup and refactoring actions:
* Updated to `FirebaseUserManager.Builder` and introducing a new `createUserManager()` factory method so it looks similar to how other helper classes are initialized in the auth package.
* `HttpRequestInfo` now supports setting URL query parameters. Calling classes no need to use `GenericUrl`.
* `JsonObjectParser` attribute is removed from the `ErrorHandlingHttpClient`. It's not needed there due to the way we parse response payloads in the SDK.

chore: Support for specifying query parameters in HttpRequestInfo

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/ListProviderConfigsPage.java
src/main/java/com/google/firebase/auth/OidcProviderConfig.java
src/main/java/com/google/firebase/auth/multitenancy/ListTenantsPage.java

Fixing the following javadoc warnings:
```
[WARNING] Javadoc Warnings
[WARNING] ~/hkj/Projects/firebase-admin-java/public/src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java:798: warning 101: Unresolved link/see tag "IllegalArgumentException" in com.google.firebase.auth.AbstractFirebaseAuth
[WARNING] ~/hkj/Projects/firebase-admin-java/public/src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java:820: warning 101: Unresolved link/see tag "IllegalArgumentException" in com.google.firebase.auth.AbstractFirebaseAuth
[WARNING] ~/hkj/Projects/firebase-admin-java/public/src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java:873: warning 101: Unresolved link/see tag "IllegalArgumentException" in com.google.firebase.auth.AbstractFirebaseAuth
[WARNING] …
```

fix: Fixing a series of javadoc warnings

---

pom.xml
src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseTokenUtils.java
src/main/java/com/google/firebase/auth/multitenancy/TenantAwareFirebaseAuth.java
src/main/java/com/google/firebase/auth/multitenancy/TenantManager.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/auth/FirebaseTokenVerifierImplTest.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/MockTokenVerifier.java
src/test/java/com/google/firebase/auth/multitenancy/TenantAwareFirebaseAuthTest.java

* Upgraded some Maven plugins to latest to avoid some issues with Jacoco code coverage reporting in older versions.
* Cleaned up the `Builder` APIs in `FirebaseAuth` and `TenantAwareFirebaseAuth`.
* Moved session cookie creation and verification APIs to `AbstractFirebaseAuth` so they are inherited by both subclasses of this API.
* Implemented support for verifying tenant-scoped session cookies (by passing a tenant ID to the respective `FirebaseTokenVerifier`).
* Implemented support for creating tenant-scoped session cookies (by verifying the ID token locally which also matches tenant IDs) 
RELEASE NOTE: Exposing `createSessionCookie()` and `verifySessionCookie()` methods from the `TenantAwareFirebaseAuth` class.

feat(auth): Support for creating tenant-scoped session cookies

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java

`AbstractFirebaseAuth.Builder` has public methods `setTokenFactory` and `setUserManager` that accepts protected parameters, which cause `javadoc` errors.
This PR is based on: https://github.com/firebase/firebase-admin-java/pull/465/commits/b413c7ab64fcf2af657b55e578647559cf2bcd61

Fix javadoc error caused by having protected parameters public methods

---

src/main/java/com/google/firebase/auth/FirebaseTokenVerifierImpl.java
src/test/java/com/google/firebase/FirebaseAppTest.java
src/test/java/com/google/firebase/auth/FirebaseTokenVerifierImplTest.java
src/test/java/com/google/firebase/auth/multitenancy/TenantAwareFirebaseAuthIT.java

`FirebaseAuth` should be able to verify ID tokens regardless of the tenant ID.
Resolves #474

fix(auth): Support verifying tenant ID tokens in FirebaseAuth

---

src/main/java/com/google/firebase/FirebaseApp.java
src/main/java/com/google/firebase/ImplFirebaseTrampolines.java
src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/FirebaseAuth.java
src/main/java/com/google/firebase/auth/multitenancy/TenantAwareFirebaseAuth.java
src/main/java/com/google/firebase/cloud/StorageClient.java
src/main/java/com/google/firebase/database/FirebaseDatabase.java
src/main/java/com/google/firebase/iid/FirebaseInstanceId.java
src/main/java/com/google/firebase/internal/FirebaseService.java
src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
src/main/java/com/google/firebase/projectmanagement/FirebaseProjectManagement.java
src/main/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImpl.java
src/test/java/com/google/firebase/FirebaseAppTest.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/iid/FirebaseInstanceIdTest.java

We have a mechanism in place to tear down any SDK state and managed resources upon calling `FirebaseApp.delete()`. However the way this is used and enforced across services is inconsistent at the moment:
* `FirebaseAuth` uses some complex and repetitive logic to throw errors from all methods after `delete()` has been called.
* Most other services (e.g. `FirebaseMessaging`) do not bother with this.
**In order to simplify the service implementations and make them consistent I'm proposing the following changes:**
1. `FirebaseAuth` doesn't have any state that requires explicit tear down. Therefore remove the existing repetitive logic for throwing errors after `delete()` is called. 
2. Make the `FirebaseService.destroy()` method non-abstract so that child classes are not forced to provide a …

fix: Cleaning up FirebaseApp state management

---

src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClient.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImpl.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigException.java
src/main/java/com/google/firebase/remoteconfig/RemoteConfigErrorCode.java
src/main/java/com/google/firebase/remoteconfig/RemoteConfigTemplate.java
src/main/java/com/google/firebase/remoteconfig/internal/RemoteConfigServiceErrorResponse.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImplTest.java

- Add `FirebaseRemoteConfigClient` interface and implementation
- Add basic classes for error handing
- Add unit tests for `FirebaseRemoteConfigClientImpl`
Note: merging to `remote-config` branch.
Related issue: #446

Add initial classes for Remote Config API

---

src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImpl.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigException.java
src/main/java/com/google/firebase/remoteconfig/RemoteConfigTemplate.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
src/test/java/com/google/firebase/remoteconfig/MockRemoteConfigClient.java

- Add the entry point for Remote Config services `FirebaseRemoteConfig.java`
- Add unit tests to cover `getTemplate()` and `getTemplateAsync()`
- Integration tests will be added later once all the operations are implemented
Issue: #446 
Note: Merging to `remote-config` branch.

Add the entry point for Remote Config

---

src/main/java/com/google/firebase/auth/internal/CryptoSigners.java
src/test/java/com/google/firebase/auth/FirebaseCustomTokenTest.java
src/test/java/com/google/firebase/auth/internal/CryptoSignersTest.java

Point all SignBlob calls to IAMCredentials
Discussed with Hiranya and Bassam
Also changed the testing codes
No API change, just internal mechanism change

fix(auth): Migrate IAM SignBlob to IAMCredentials SignBlob

---

src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImpl.java
src/main/java/com/google/firebase/remoteconfig/RemoteConfigParameter.java
src/main/java/com/google/firebase/remoteconfig/RemoteConfigParameterValue.java
src/main/java/com/google/firebase/remoteconfig/RemoteConfigTemplate.java
src/main/java/com/google/firebase/remoteconfig/internal/TemplateResponse.java

- Refactor `public` and `response` types
- Change the `response` DTOs to simple java beans (with getters and setters)
- Add `protected` `ctors` to `public` types to initialize from the corresponding `response` types

Remote Config Refactor Public and Response types

---

src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClient.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImpl.java
src/main/java/com/google/firebase/remoteconfig/Parameter.java
src/main/java/com/google/firebase/remoteconfig/ParameterValue.java
src/main/java/com/google/firebase/remoteconfig/Template.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImplTest.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
src/test/java/com/google/firebase/remoteconfig/MockRemoteConfigClient.java

- Based on the API review decision (go/admin-java-sdk-remote-config), Remove `RemoteConfig` prefix from classes

Remove RemoteConfig prefix from classes

---

src/test/java/com/google/firebase/snippets/FirebaseMessagingSnippets.java

Multicast message can send up to 500 messages, not 100
https://github.com/firebase/firebase-admin-java/blob/408b85f7d0072e8fb3b462aa2317843d683e7ad7/src/main/java/com/google/firebase/messaging/MulticastMessage.java#L46

Fix comment about max number of events

---

src/main/java/com/google/firebase/remoteconfig/Condition.java
src/main/java/com/google/firebase/remoteconfig/TagColor.java
src/main/java/com/google/firebase/remoteconfig/Template.java
src/main/java/com/google/firebase/remoteconfig/internal/TemplateResponse.java
src/test/java/com/google/firebase/remoteconfig/ConditionTest.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImplTest.java
src/test/resources/getRemoteConfig.json

- Add Remote Config Conditions
- Add unit tests
Related Issue: #446

Add Remote Config conditions to template

---

src/main/java/com/google/firebase/remoteconfig/Parameter.java
src/main/java/com/google/firebase/remoteconfig/ParameterGroup.java
src/main/java/com/google/firebase/remoteconfig/ParameterValue.java
src/main/java/com/google/firebase/remoteconfig/Template.java
src/main/java/com/google/firebase/remoteconfig/internal/TemplateResponse.java
src/test/java/com/google/firebase/remoteconfig/ConditionTest.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImplTest.java
src/test/java/com/google/firebase/remoteconfig/ParameterGroupTest.java
src/test/java/com/google/firebase/remoteconfig/ParameterTest.java
src/test/java/com/google/firebase/remoteconfig/ParameterValueTest.java
src/test/java/com/google/firebase/remoteconfig/TemplateTest.java
src/test/resources/getRemoteConfig.json

- Add Remote Config Parameter Group type
- Implement `equals()` in all public RC types
- Add unit tests for public RC types
- Refactor existing unit tests to use `equals()` when comparing templates

Add Remote Config Parameter Group type

---

src/main/java/com/google/firebase/remoteconfig/Template.java
src/main/java/com/google/firebase/remoteconfig/User.java
src/main/java/com/google/firebase/remoteconfig/Version.java
src/main/java/com/google/firebase/remoteconfig/internal/TemplateResponse.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImplTest.java
src/test/java/com/google/firebase/remoteconfig/TemplateTest.java
src/test/java/com/google/firebase/remoteconfig/UserTest.java
src/test/java/com/google/firebase/remoteconfig/VersionTest.java
src/test/resources/getRemoteConfig.json

- Add Version information to the Template
- Create new Version type
- Create new User type
- ~Note: Since Version and User types are output only, I did not implement `equal()` and `hashcode()` operations. Instead, unit tests are checking for each property in `Version` and `User` individually. I also removed the equality operations from `Template`, as well.~
- Based on PR review feedback, implement equality in all public types (including `Version` and `User`) to keep consistency.

Add Version information to RC template

---

src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClient.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImpl.java
src/main/java/com/google/firebase/remoteconfig/PublishOptions.java
src/main/java/com/google/firebase/remoteconfig/internal/PublishOptions.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImplTest.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
src/test/java/com/google/firebase/remoteconfig/MockRemoteConfigClient.java
src/test/resources/getRemoteConfig.json

- Add `getTemplateAtVersion()`, `publishTemplate()`, `validateTemplate()`, and `forcePublishTemplate()` operations.
- Add unit tests for new operations.
- Add new unit test for timestamps with up to nanoseconds precision.

Add Remote Config Pubish, Validate, and GetTemplateAtVersion operations

---

src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClient.java
src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImpl.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImplTest.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
src/test/java/com/google/firebase/remoteconfig/MockRemoteConfigClient.java

- Add `rollback` operations
- Add unit tests
Related to #446

Add Remote Config rollback operation

---

src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIT.java

- Add Remote Config Integration tests
Note: Added `release:stage` to trigger integration tests

Add Remote Config Integration tests

---

src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIT.java

- Refactor RC integration tests by adding separate test per operation

chore(rc): Refactor RC integration tests

---

src/main/java/com/google/firebase/messaging/FirebaseMessagingClientImpl.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingClientImplTest.java

FCM service seems to occasionally respond with non-json (HTML) error responses, and if these responses contain certain special characters (e.g. `[` or `]`), the SDK throws a cryptic JSON parse exception (see #506). 
The `MessagingErrorHandler` is supposed to catch all parse errors, but today it only handles IOExceptions thrown by the parser. But in the above case parser throws an IllegalArgumentException. This PR addresses this issue by updating the `MessagingErrorHandler` to catch *all* exceptions thrown by the parser. This makes sure the developer gets a `FirebaseMessagingException` with the original error response attached to it, when the above error condition occurs.
RELEASE NOTE: Improved support for handling certain non-JSON error responses sent by the FCM backend service.

fix(fcm): Gracefully handling non-json error responses

---

pom.xml
src/main/java/com/google/firebase/auth/FirebaseUserManager.java
src/main/java/com/google/firebase/auth/multitenancy/FirebaseTenantClient.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/multitenancy/FirebaseTenantClientTest.java

Add support for Auth emulator.
More info: 
- Issue: #493
- Firebase: https://firebase.google.com/docs/emulator-suite/connect_auth#environment-variable

Add Firebase auth emulator

---

src/main/java/com/google/firebase/messaging/FirebaseMessaging.java

Update doc string for dryRun in FCM send methods to mention that it cannot be used to validate APNS tokens.

Update doc string for dryRun in FCM send methods.

---

src/main/java/com/google/firebase/auth/OidcProviderConfig.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/OidcProviderConfigTest.java
src/test/java/com/google/firebase/auth/multitenancy/TenantAwareFirebaseAuthIT.java
src/test/resources/listOidc.json
src/test/resources/oidc.json

Provides an option for developers to specify the OAuth response type for their OIDC provider (either one of these can be set:):
- id_token
- code (if set, must also set the client secret)

feat: enables OIDC auth code flow

---

.github/workflows/nightly.yml
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIT.java

- Add nightly build workflow.
- Add a failing test to trigger the email notifications.
Note: Adding `release:stage` label to trigger integration tests. Integration tests should fail in this PR.

chore: Add nightly build workflow

---

.github/workflows/nightly.yml

- Added the missing version info: `@master` for send-email action.

Fix send-email action version in nightly workflow

---

src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementIT.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIT.java

- Remove the failing integration test added in #524 to test the nightly email notifications (the test runs are completed).
- Remove SHA1 tests related to b/185268518
Note: staging to trigger integration tests. All tests should pass.

Remove the failing integration tests

---

.github/dependabot.yml

This hopefully helps prevent dependencies falling behind. See #533 
More info on dependabot updates at https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates

chore: Setup a Dependabot for dependency updates

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/UserRecord.java

Auth Javadoc edits

---

src/main/java/com/google/firebase/auth/AuthErrorCode.java
src/main/java/com/google/firebase/auth/internal/AuthErrorHandler.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

Catch EMAIL_NOT_FOUND when /accounts:sendOobCode is called for password reset on a user that does not exist.

fix(auth): adds missing EMAIL_NOT_FOUND error code

---

src/main/java/com/google/firebase/auth/OidcProviderConfig.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/OidcProviderConfigTest.java
src/test/java/com/google/firebase/auth/multitenancy/TenantAwareFirebaseAuthIT.java
src/test/resources/listOidc.json
src/test/resources/oidc.json

Provides an option for developers to specify the OAuth response type for their OIDC provider (either one of these can be set:):
- id_token
- code (if set, must also set the client secret)

feat(auth): enables OIDC auth code flow

---

pom.xml

Reverts firebase/firebase-admin-java#562
It appears that the `maven-javadoc-plugin 3.3.0` breaks the build flow in Java 1.7. Reverting this until we come up with a proper solution.
CI error: https://github.com/firebase/firebase-admin-java/runs/2784537466?check_suite_focus=true

Revert "chore(deps): bump maven-javadoc-plugin from 3.2.0 to 3.3.0"

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
pom.xml
src/main/java/com/google/firebase/FirebaseApp.java
src/main/java/com/google/firebase/FirebaseOptions.java
src/main/java/com/google/firebase/auth/internal/Utils.java
src/main/java/com/google/firebase/database/util/EmulatorHelper.java
src/main/java/com/google/firebase/internal/ApplicationDefaultCredentialsProvider.java
src/main/java/com/google/firebase/internal/FirebaseProcessEnvironment.java
src/test/java/com/google/firebase/FirebaseAppTest.java
src/test/java/com/google/firebase/auth/EmulatorFirebaseTokenVerifierImplTest.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java
src/test/java/com/google/firebase/auth/FirebaseTokenUtilsTest.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/multitenancy/FirebaseTenantClientTest.java
src/test/java/com/google/firebase/database/FirebaseDatabaseTest.java
src/test/java/com/google/firebase/testing/IntegrationTestUtils.java
src/test/java/com/google/firebase/testing/TestUtils.java

This makes it possible to upgrade a wide range of the tools/dependencies we use. We will continue to compile source down to Java 1.7 compatibility (required config already present in `pom.xml`), and therefore the resulting artifacts will work on Java 7. Added Java 7, 8 and 11 to the CI build matrix for added coverage.
Environment variable manipulation in tests do not work on Java 8 and above, and therefore implemented some workarounds for that too.

fix: Using Java 8 in release and nightly builds

---

src/main/java/com/google/firebase/internal/ApiClientUtils.java
src/test/java/com/google/firebase/internal/ApiClientUtilsTest.java

[Google Cloud documentation](https://cloud.google.com/apis/design/errors#retrying_errors) has been updated to not consider 500 as a retryable error code. Update Admin SDK to align with that

Drop 500 from the retryable errorcode list

---

.github/scripts/package_artifacts.sh

Set `trimStackTrace` to `false` in mvn failsafe plugin.
This will print the full stack trace for failed integration tests making it easier to investigate nightly build failures.

Set trimStackTrace property to false

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/AuthErrorCode.java
src/main/java/com/google/firebase/auth/RevocationCheckDecorator.java
src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
src/test/java/com/google/firebase/auth/FirebaseAuthTest.java

When `verifyIdToken` or `verifySessionCookie` is called with `checkResolved` set to `true` we also check if the user is disabled. If so, a `FirebaseAuthException` with the new AuthErrorCode `USER_DISABLED` is thrown.

fix(auth): check if the user is disabled on checkRevoked=true for verifyIdToken and verifySessionCookie

---

src/main/java/com/google/firebase/FirebaseOptions.java
src/test/java/com/google/firebase/FirebaseOptionsTest.java

Use provided by Builder objects prior to init defaults.
Avoid `ClassNotFoundException` when JacksonFactory excluded
```
FirebaseOptions.builder()
.setJsonFactory(Utils.getDefaultJsonFactory())
.build()
``````
<dependency>
<groupId>com.google.firebase</groupId>
<artifactId>firebase-admin</artifactId>
<exclusions>
<exclusion>
<groupId>com.google.http-client</groupId>
<artifactId>google-http-client-jackson2</artifactId>
</exclusion>
</exclusions>
</dependency>
```

fix: FirebaseOptions: move default initialization from Builder

---

pom.xml

- Starting with version 3.0 `javadoc` uses [updated parameter names](https://maven.apache.org/plugins/maven-javadoc-plugin/examples/alternate-doclet.html) in custom Doclet configurations, which affects our internal devsite scripts.
-  This PR updates the config to use the new parameters names.
- Tested and verified with the devsite script.

Update custom Doclet configuration for javadoc

---

src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java

* Adds Argon2 Java snippet for Firebase docs.
* Original issue: #636 
* N/A. API tested in #637

Add Argon2 Java snippet

---

README.md

RELEASE NOTE: Deprecated support for Java 7. Developers are advised to use Java 8 or higher when deploying the Admin SDK. Java 7 support will be dropped in the next major version.

change: Deprecated support for Java 7

---

.github/workflows/ci.yml
README.md
pom.xml

- Updated the minimum support platform version to Java 8
- Updated the CIs to run on Java 8, 11, and 17
- Upgraded the dependencies that were blocked on Java 7, including `libraries-bom`
- Fixes #678, #660, #655
RELEASE NOTE: Dropped support for Java 7. Developers should use Java 8 or higher when deploying the Admin SDK.
RELEASE NOTE: Upgraded the dependency on `libraries-bom` to v25 and higher. This in turns upgrades the dependencies on `google-cloud-firestore` and `google-cloud-storage` to the latest versions.

change: Drop support for Java 7

---

pom.xml

Breaking change: Dropped support for Java 7. Developers should use Java 8 or higher when deploying the Admin SDK.
Breaking change: Upgraded the dependency on `libraries-bom` to v25 and higher. This in turns upgrades the dependencies on `google-cloud-firestore` and `google-cloud-storage` to the latest versions.

[chore] Release 9.0.0

---

CONTRIBUTING.md
pom.xml

- Updated maven source config to `1.8`
- Updated the `CONTRIBUTING.md` to reflect Java 8+ support.

chore: Update source target to 1.8

---

src/main/java/com/google/firebase/ImplFirebaseTrampolines.java
src/main/java/com/google/firebase/database/FirebaseDatabase.java
src/main/java/com/google/firebase/internal/EmulatorCredentials.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/multitenancy/FirebaseTenantClientTest.java

If `FIREBASE_AUTH_EMULATOR_HOST` env var is set the SDK shouldn't connect to Auth servers for OAuth2 handshake. This PR sets the emulator credentials when emulator mode is set.
b/220373445

fix(auth): Set emulator credentials when using the Auth emulator

---

src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java

I was testing the code snippets in FirebaseAuthSnippets.java, which would be used this doc https://cloud.google.com/identity-platform/docs/multi-tenancy-managing-tenants#controlling_access_with_custom_claims. When testing the setCustomUserClaims(), I got an USER_NOT_FOUND error. 
"No user record found for the given identifier (USER_NOT_FOUND)."
I believe this error happens because `FirebaseAuth.getInstance()` doesn’t specify which tenant we are setting.
Therefore, using TenantAwareAuth instance for the corresponding tenant `tenantAuth` instead of `FirebaseAuth.getInstance()` fixes the issue.

Fix a small bug in setCustomUserClaims() auth snippet

---

src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java

**Issue**: Using the [importWithScrypt()](https://github.com/firebase/firebase-admin-java/blob/master/src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java#L566) code snippet in the [public doc](https://firebase.google.com/docs/auth/admin/import-users#import_users_with_firebase_scrypt_hashed_passwords) will successfully import the user, but we will be unable to sign in because the password is changed.
This may be similar to this issue in Firebase Admin Go: [https://github.com/firebase/firebase-admin-go/issues/479](https://www.google.com/url?q=https://github.com/firebase/firebase-admin-go/issues/479&sa=D&source=buganizer&usg=AOvVaw1NQR0Ya_HBNq6nQolmle6w) and the fixes in [https://github.com/firebase/firebase-admin-go/pull/480](https://www.google.com/url?q=https://github.com/f …

Update passwordHash and passwordSalt to be base64 decoded before user import

---

pom.xml
src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingIT.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java

1. Add `sendEach`, `sendEachAsync`, `sendEachForMulticast` and `sendEachForMulticastAsync`
2. Deprecate `sendAll`, `sendAllAsync`, `sendMulticast` and `sendMulticastAsync`
`sendEach` vs `sendAll`
1. `sendEach` sends one HTTP request to V1 Send endpoint for each
message in the array.
`sendAll` sends only one HTTP request to V1 Batch Send endpoint
to send all messages in the array.
3. `sendEach` calls `messagingClient.send` to send each message
and constructs a `SendResponse` with the returned `messageId`.
If `messagingClient.send` throws out an exception, `sendEach`
will catch the exception and also turn it into a `SendResponse`
with the exception in it.
`sendEach` calls `ApiFutures.allAsList().get()` to execute all
`messagingClient.send` calls asynchronously and wait for all of
them to …

feat(fcm): Implement `sendEach`, `sendEachAsync`, `sendEachForMulticast` and `sendEachForMulticastAsync`

---

pom.xml
src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingIT.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java

* Add org.hamcrest as dependency for unit tests
* Implement sendEach, sendEachAsync, sendEachForMulticast and sendEachForMulticastAsync
`sendEach` vs `sendAll`
1. `sendEach` sends one HTTP request to V1 Send endpoint for each message in the array. `sendAll` sends only one HTTP request to V1 Batch Send endpoint to send all messages in the array.
2. `sendEach` calls `messagingClient.send` to send each message and constructs a `SendResponse` with the returned `messageId`. If `messagingClient.send` throws out an exception, `sendEach` will catch the exception and also turn it into a `SendResponse` with the exception in it. `sendEach` calls `ApiFutures.allAsList().get()` to execute all `messagingClient.send` calls asynchronously and wait for all of them to complete and construct a …

feat(fcm): Implement `sendEach`, `sendEachAsync`, `sendEachForMulticast` and `sendEachForMulticastAsync` (#785)

---

src/main/java/com/google/firebase/messaging/FirebaseMessaging.java

In d1baee36 all `sendAll` and `sendMulticast` variants were deprecated, however those methods were marked as deprecated only in javadoc but not using `@Deprecated`.
This commit adds `@Deprecated` annotation where needed, in order to better signal the deprecation to developers.

Mark `sendAll` and `sendMulticast` variants as deprecated

---

src/main/java/com/google/firebase/FirebaseOptions.java
src/main/java/com/google/firebase/internal/FirebaseRequestInitializer.java
src/test/java/com/google/firebase/FirebaseOptionsTest.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/internal/FirebaseRequestInitializerTest.java

fix: Make writeTimeout configurable (similar to readTimeout)

---

src/main/java/com/google/firebase/FirebaseOptions.java

Fix doc strings in #900

---

src/main/java/com/google/firebase/database/utilities/Utilities.java

chore: Migrate from Charsets to StandardCharsets

---

src/main/java/com/google/firebase/internal/FirebaseThreadManagers.java
src/main/java/com/google/firebase/messaging/FirebaseMessaging.java

- The default thread manger now limits to 100 threads. This resolves OOM errors that come with threads used to send large amounts of FCM messages. 
- Deadlock scenario in `sendEachAsync()` and `sendEachForMulticastAsync()` is now avoided by chaining ApiFutures

fix: Limit default `ThreadPoolExecutor` thread count and remove deadlock scenario

---

pom.xml
src/test/java/com/google/firebase/internal/ApacheHttp2TransportIT.java

fix(deps): Remove mockserver dependency

---

src/main/java/com/google/firebase/internal/ErrorHandlingHttpClient.java
src/main/java/com/google/firebase/internal/SdkUtils.java
src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java
src/test/java/com/google/firebase/auth/internal/CryptoSignersTest.java
src/test/java/com/google/firebase/auth/multitenancy/FirebaseTenantClientTest.java
src/test/java/com/google/firebase/auth/multitenancy/TenantAwareFirebaseAuthTest.java
src/test/java/com/google/firebase/iid/FirebaseInstanceIdTest.java
src/test/java/com/google/firebase/internal/ErrorHandlingHttpClientTest.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingClientImplTest.java
src/test/java/com/google/firebase/messaging/InstanceIdClientImplTest.java
src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImplTest.java
src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientImplTest.java

Includes:
- Auth
- Installations / Instance ID
- Messaging
- Topic Management
- Project Management
- Remote Config
This does not include:
- Firestore
- RTDB
- Storage

chore: Add `X-Goog-Api-Client` metric header to outgoing requests

---

src/main/java/com/google/firebase/internal/ApiClientUtils.java
src/test/java/com/google/firebase/internal/ApacheHttp2TransportIT.java
src/test/java/com/google/firebase/internal/ApiClientUtilsTest.java

This fixes an unintentional change in `ApiClientUtils.getDefaultTransport()` which caused firebaseOptions to create a new instance of the default transport on `firebaseOptions` build. This only affected developers who made multiple calls to `FirebaseOptions.builder(...).build()` or initialized multiple app instances.

fix: `ApiClientUtils.getDefaultTransport()` should return a cached instance to an `ApacheHttp2Transport`

---

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java
src/main/java/com/google/firebase/auth/UserRecord.java

Simple fix for string comparison.
From what I could see these changes are already covered by unit tests and I was not sure how to add new ones to test this specific scenario.

fix: use .equals() instead of == for strings

---

pom.xml

Following https://github.com/firebase/firebase-admin-java/issues/1045
Changes:
- Remove the duplicate google-api-client-bom as it is already part of libaries-bom
- Move google-auth-library-oauth2-http in front of google-api-client. This is to help ensure that the two auth modules (oauth2 and credentials) have the versions match. Maven's dep resolution strategy searches the path of the first deps it sees if the possible deps have the same number of layers away (https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies)

chore: Rearrange firebase admin pom deps

---

src/main/java/com/google/firebase/messaging/AndroidNotification.java
src/test/java/com/google/firebase/messaging/MessageTest.java

added proxy field that described on page:
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification

feat(fcm): Support `proxy` field in FCM `AndroidNotification`

---

.github/workflows/release.yml

Preemptively fixing release issue similar to https://github.com/firebase/firebase-admin-node/pull/2867

chore: Updated release GHA to have write permissions

---

src/main/java/com/google/firebase/messaging/ApnsConfig.java
src/test/java/com/google/firebase/messaging/FirebaseMessagingIT.java
src/test/java/com/google/firebase/messaging/MessageTest.java

Adds a new `liveActivityToken` field to the `ApnsConfig` class, allowing you to specify a Live Activity token for APNS messages.
The changes include:
- Addition of the `liveActivityToken` field in `ApnsConfig.java` and its associated builder.
- Updates to unit tests in `MessageTest.java` to verify the correct serialization of the new field and to include it in existing test cases. A new test method `testApnsMessageWithOnlyLiveActivityToken` was added for specific testing.
- Update to the integration test in `FirebaseMessagingIT.java` to include the `liveActivityToken` in a test message.

feat(fcm): Add `liveActivityToken` to `ApnsConfig`

---

src/test/java/com/google/firebase/snippets/FirebaseMessagingSnippets.java

Adds sendEach based snippets for FCM.

---

src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java

chore: Update tests for getting and deleting provider uid via phone number and email.
