src/main/java/com/google/firebase/FirebaseOptions.java, src/main/java/com/google/firebase/ThreadManager.java, src/main/java/com/google/firebase/auth/FirebaseCredential.java, src/main/java/com/google/firebase/auth/FirebaseCredentials.java, src/main/java/com/google/firebase/tasks/Task.java
Some left over API docs updates from the recent changes.
=> Updated API docs

src/main/java/com/google/firebase/internal/GaeThreadFactory.java
Related to #55 
Thanks to @nilsonpontello for pointing it out.
=> Changing log level to info

src/main/java/com/google/firebase/auth/FirebaseAuth.java, src/test/java/com/google/firebase/auth/FirebaseAuthIT.java
go/firebase-admin-custom-claims
=> Renamed method as per the proposed API

src/main/java/com/google/firebase/auth/ExportedUserRecord.java, src/main/java/com/google/firebase/auth/FirebaseAuth.java, src/main/java/com/google/firebase/auth/FirebaseUserManager.java, src/main/java/com/google/firebase/auth/ListUsersPage.java, src/main/java/com/google/firebase/auth/UserRecord.java, src/main/java/com/google/firebase/auth/internal/DownloadAccountResponse.java, src/test/java/com/google/firebase/auth/FirebaseAuthTest.java, src/test/java/com/google/firebase/auth/FirebaseCredentialsTest.java, src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java, src/test/java/com/google/firebase/auth/ListUsersPageTest.java, src/test/java/com/google/firebase/auth/UserRecordTest.java
This is the first step towards removing `org.json:json` dependency from the codebase. This dependency has caused issues for many first-time users as indicated in #113
=> Removing all usages of org.json from the auth package.

src/main/java/com/google/firebase/database/DataSnapshot.java, src/main/java/com/google/firebase/database/DatabaseReference.java, src/main/java/com/google/firebase/database/MutableData.java, src/main/java/com/google/firebase/database/OnDisconnect.java, src/main/java/com/google/firebase/database/snapshot/PriorityUtilities.java, src/main/java/com/google/firebase/database/utilities/Validation.java, src/main/java/com/google/firebase/database/utilities/encoding/CustomClassMapper.java, src/test/java/com/google/firebase/database/MapperTest.java, src/test/java/com/google/firebase/database/integration/DataTestIT.java, src/test/java/com/google/firebase/database/integration/EventHelper.java, src/test/java/com/google/firebase/database/integration/EventTestIT.java, src/test/java/com/google/firebase/database/integration/TransactionTestIT.java, src/test/java/com/google/firebase/database/utilities/ValidationTest.java
Fix that enables serializing acceptable double values as longs. Also ported the relevant integration tests, and added a couple of unit tests of my own. Also in the PR are some overdue documentation/annotation updates. 
Resolves #116
=> Porting the fix to double serialization along with tests

pom.xml, src/test/java/com/google/firebase/auth/FirebaseAuthTest.java, src/test/java/com/google/firebase/auth/FirebaseCredentialsTest.java
Also upgrading GCS and Netty dependencies to stay in sync, and fixing a flaky auth test.
=> Upgrading Firestore to 0.33.0-beta

src/test/java/com/google/firebase/iid/FirebaseInstanceIdIT.java
fix the iid deletion integration test with a legal iid.
=> fix integration test with legal non-existing-iid

src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
Aligning the SDK with the new FCM error codes defined at https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode
=> Updated FCM error codes

CHANGELOG.md
=> Fix names of added methods in Changelog.

src/test/java/com/google/firebase/snippets/FirebaseAppSnippets.java, src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java, src/test/java/com/google/firebase/snippets/FirebaseDatabaseSnippets.java, src/test/java/com/google/firebase/snippets/FirebaseMessagingSnippets.java, src/test/java/com/google/firebase/snippets/FirebaseStorageSnippets.java
Migrated snippets from quicktart-java and snippets-java repos.
=> Adding Documentation Snippets

CHANGELOG.md, src/main/java/com/google/firebase/FirebaseOptions.java, src/main/java/com/google/firebase/auth/FirebaseAuth.java, src/main/java/com/google/firebase/auth/FirebaseUserManager.java, src/main/java/com/google/firebase/iid/FirebaseInstanceId.java, src/main/java/com/google/firebase/internal/FirebaseRequestInitializer.java, src/main/java/com/google/firebase/messaging/FirebaseMessaging.java, src/test/java/com/google/firebase/FirebaseOptionsTest.java, src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java, src/test/java/com/google/firebase/internal/FirebaseRequestInitializerTest.java
=> Support configuring timeout for outbound requests

CHANGELOG.md, pom.xml
=> Upgrading Firestore, GCS and Netty to recent versions

pom.xml, prepare_release.sh
* Updated license information in pom.xml
* Updating the changelog modify logic to not insert redundant whitespace
=> Cleaning up the release tools

src/test/java/com/google/firebase/snippets/FirebaseAuthSnippets.java
Snippets to appear on https://firebase.google.com/docs/auth/admin/import-users
=> Snippets for user import functionality

src/main/java/com/google/firebase/iid/FirebaseInstanceId.java
To be consistent with https://firebase.google.com/docs/reference/admin/node/admin.instanceId.InstanceId#deleteInstanceId
=> Updating the API docs for IID

CHANGELOG.md, src/main/java/com/google/firebase/messaging/FirebaseMessaging.java, src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java
Related to #214 
b/119428403 for more context
=> Getting more detailed errors from FCM back-end service

CHANGELOG.md, src/main/java/com/google/firebase/messaging/AndroidNotification.java, src/test/java/com/google/firebase/messaging/FirebaseMessagingTest.java, src/test/java/com/google/firebase/messaging/MessageTest.java
=> Add android channel id support

src/test/java/com/google/firebase/projectmanagement/AndroidAppTest.java, src/test/java/com/google/firebase/projectmanagement/FirebaseProjectManagementServiceImplTest.java, src/test/java/com/google/firebase/projectmanagement/IosAppTest.java, src/test/java/com/google/firebase/projectmanagement/ShaCertificateTest.java
Bumps the test coverage of the `projectmanagement` package from 84% to 92%.
=> More unit tests for project management API

src/main/java/com/google/firebase/auth/ActionCodeSettings.java, src/main/java/com/google/firebase/auth/FirebaseAuth.java
Some minor updates proposed by the docs team.
=> Some documentation updates

CHANGELOG.md, src/main/java/com/google/firebase/auth/internal/UploadAccountResponse.java, src/test/resources/importUsersError.json
Reverts firebase/firebase-admin-java#244
Fix has been made in backend server and pushed to production.
=> Revert "Fix for the uploadAccountResponse for correct error message/reason"

src/test/java/com/google/firebase/snippets/FirebaseMessagingSnippets.java
Samples to appear in the documentation
=> Snippets for FCM sendAll() and sendMulticast()

pom.xml, src/main/java/com/google/firebase/auth/FirebaseTokenVerifierImpl.java
Upgraded Firestore to 1.1.0, and some of the other related dependencies.
=> Upgraded Firestore and other gcloud dependencies

CHANGELOG.md, pom.xml
=> Upgrades Firestore and Storage dependencies

src/main/java/com/google/firebase/messaging/AndroidNotification.java
=> Fix a typo in the comment

CONTRIBUTING.md
=> Update to fix broken link

src/main/java/com/google/firebase/database/util/EmulatorHelper.java
FIREBASE_DATABASE_EMULATOR_HOST is the correct one.
=> Fix emulator env var name.

src/main/java/com/google/firebase/FirebaseOptions.java
=> Minor fix to docs (broken link: GoogleCredentials)

pom.xml
- Admin Java SDK Release 6.11.0
=> Admin Java SDK Release 6.11.0

pom.xml
=> Staged Release 6.12.0

.github/workflows/ci.yml, .github/workflows/maven.yml
=> Setting up a CI pipeline based on GitHub Actions

pom.xml
=> Staged Release 6.12.1

pom.xml
=> Staged Release 6.12.2

src/test/java/com/google/firebase/FirebaseOptionsTest.java, src/test/java/com/google/firebase/database/utilities/ValidationTest.java
Updated some tests that were resulting in compiler warnings due to bad use of generics or otherwise deprecated APIs.
=> Fixing some deprecated API usages

pom.xml, src/main/java/com/google/firebase/auth/FirebaseUserManager.java
This dependency was added in #387, however, I didn't end up keeping the AutoValue classes I had created.
=> Remove unused AutoValue dependency.

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java, src/main/java/com/google/firebase/auth/FirebaseUserManager.java, src/test/java/com/google/firebase/auth/FirebaseAuthIT.java, src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java, src/test/java/com/google/firebase/auth/ProviderConfigTestUtils.java, src/test/java/com/google/firebase/auth/TenantAwareFirebaseAuthIT.java
Adds a get operation for SAML provider configs. I've included both unit tests and integration tests.
=> Add get operation for SAML provider configs.

src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java, src/main/java/com/google/firebase/auth/FirebaseUserManager.java, src/main/java/com/google/firebase/auth/SamlProviderConfig.java, src/test/java/com/google/firebase/auth/FirebaseAuthIT.java, src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java, src/test/java/com/google/firebase/auth/TenantAwareFirebaseAuthIT.java
Adds an update operation for SAML provider configs. I've included both unit tests and integration tests.
=> Add operation to update SAML provider configs.

pom.xml
Upgraded Firestore, GCS, Google API client and others.
=> chore: Upgraded GCP and other util dependencies

src/main/java/com/google/firebase/messaging/AndroidConfig.java, src/test/java/com/google/firebase/messaging/MessageTest.java
Support direct_boot_ok parameter in AndroidConfig. 
* Updated the related tests.
=> feat(fcm): Support direct_boot_ok parameter

src/main/java/com/google/firebase/messaging/AndroidConfig.java
- Fix documentation strings
- Bye bye, `will` :)
=> Fix documentation strings in Android Notification

src/main/java/com/google/firebase/messaging/FirebaseMessagingClientImpl.java
`new Batch()` is deprecated in the latest versions of Google API client. Instead we should use `GoogleClient.batch()` method.
=> fix(fcm): Replacing deprecated Batch API constructor

pom.xml
Major version with new error handling APIs.
=> [chore] Release 7.0.0

pom.xml
- Release 7.1.0
- Includes Remote Config API #446
=> [chore] Release 7.1.0

ISSUE_TEMPLATE.md
- Remove delayed response message for holidays
=> Remove delayed response message for holidays

pom.xml
=> [chore] Release 7.1.1

src/main/java/com/google/firebase/auth/OidcProviderConfig.java, src/test/java/com/google/firebase/auth/FirebaseAuthIT.java, src/test/java/com/google/firebase/auth/FirebaseUserManagerTest.java, src/test/java/com/google/firebase/auth/OidcProviderConfigTest.java, src/test/java/com/google/firebase/auth/multitenancy/TenantAwareFirebaseAuthIT.java, src/test/resources/listOidc.json, src/test/resources/oidc.json
Reverts firebase/firebase-admin-java#522
Reverting until launch review is complete.
=> Revert "feat: enables OIDC auth code flow"

pom.xml
=> [chore] Release v7.3.0

src/main/java/com/google/firebase/messaging/AndroidConfig.java
Together with a doc CL, this addresses internal bug 189890961.
Thanks!
=> Adding detail RE default value of collapse key.

pom.xml
=> [chore] Release 8.0.0

pom.xml
=> [chore] Release 8.2.0

pom.xml
Reverts firebase/firebase-admin-java#683
=> Revert "[chore] Release 8.2.0"

pom.xml
- Take 2, trying again to see if the gpg key issue was temporary before cycling the keys.
=> [chore] Release 8.2.0 Take 2

pom.xml
=> [chore] Release 9.1.0

pom.xml
=> [chore] Release 9.1.1

pom.xml
=> [chore] Release 9.2.0

pom.xml
=> [chore] Release 9.4.0

pom.xml
=> [chore] Release 9.4.1

src/main/java/com/google/firebase/auth/FirebaseToken.java
Fixing typo noted in b/181365473.
=> Fix typo in FirebaseToken.java

src/test/java/com/google/firebase/cloud/StorageClientIT.java
Changed bucket name to be globally unique and un-used.
=> chore: Fix non-existing bucket test

pom.xml
Reverts firebase/firebase-admin-java#1125
=> Revert "[chore] Release 9.6.0"
